"""baseline schema

Autogenerated from the SQLAlchemy models, plus the pieces the old startup sync used to add by hand
(work-order-type check, performance indexes).

Databases created before Alembic (the live Neon DB, local dev DBs) already have these tables. For them
`upgrade()` brings the shape up to date with the legacy sync and records the revision without recreating
anything, so `alembic upgrade head` is safe on both fresh and existing databases.

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 11:40:53.147390
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def _create_baseline() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('event_table',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_date', sa.String(), nullable=False),
    sa.Column('event_time', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_table_event_id'), 'event_table', ['event_id'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_notification_id'), 'notification', ['notification_id'], unique=False)
    op.create_table('nursery',
    sa.Column('nursery_id', sa.String(), nullable=False),
    sa.Column('nursery_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('nursery_id')
    )
    op.create_index(op.f('ix_nursery_nursery_id'), 'nursery', ['nursery_id'], unique=False)
    op.create_table('user_table',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('hourly_rate_multiplier', sa.Numeric(precision=14, scale=6), server_default='1.000000', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('admin', 'employee', 'nursery', 'head_installation', 'head_maintenance')", name='role_check'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_table_user_id'), 'user_table', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_table_user_username'), 'user_table', ['user_username'], unique=True)
    op.create_table('zone_configuration',
    sa.Column('zone_number', sa.Integer(), nullable=False),
    sa.Column('subzone_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zone_number')
    )
    op.create_index(op.f('ix_zone_configuration_zone_number'), 'zone_configuration', ['zone_number'], unique=False)
    op.create_table('order_table',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('work_order_type', sa.String(length=20), server_default='INSTALL', nullable=False),
    sa.Column('designer_name', sa.String(length=50), nullable=True),
    sa.Column('total_order_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', name='order_status_enum'), server_default='CREATED', nullable=False),
    sa.Column('ordered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_table_order_id'), 'order_table', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_table_user_id'), 'order_table', ['user_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('nursery_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), server_default=sa.text("'tree'"), nullable=False),
    sa.Column('zones', sa.Integer(), nullable=False),
    sa.Column('subzone', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('gallons', sa.String(), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('base_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nursery_id'], ['nursery.nursery_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_nursery_id'), 'product', ['nursery_id'], unique=False)
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=False)
    op.create_table('product_submission',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('nursery_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), server_default=sa.text("'tree'"), nullable=False),
    sa.Column('zones', sa.Integer(), nullable=False),
    sa.Column('subzone', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('gallons', sa.String(), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('approved_product_id', sa.String(), nullable=True),
    sa.Column('barcode_status', sa.String(), server_default=sa.text("'NOT_SET'"), nullable=False),
    sa.Column('barcode_printed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('barcode_printed_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['barcode_printed_by'], ['user_table.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['user_table.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nursery_id'], ['nursery.nursery_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_table.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_product_submission_approved_product_id'), 'product_submission', ['approved_product_id'], unique=False)
    op.create_index(op.f('ix_product_submission_barcode_printed_by'), 'product_submission', ['barcode_printed_by'], unique=False)
    op.create_index(op.f('ix_product_submission_employee_id'), 'product_submission', ['employee_id'], unique=False)
    op.create_index(op.f('ix_product_submission_nursery_id'), 'product_submission', ['nursery_id'], unique=False)
    op.create_index(op.f('ix_product_submission_reviewed_by'), 'product_submission', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_product_submission_submission_id'), 'product_submission', ['submission_id'], unique=False)
    op.create_table('employee_scan_log',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('scanned_quantity', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['user_table.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order_table.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_employee_scan_log_employee_id'), 'employee_scan_log', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_scan_log_order_id'), 'employee_scan_log', ['order_id'], unique=False)
    op.create_index(op.f('ix_employee_scan_log_product_id'), 'employee_scan_log', ['product_id'], unique=False)
    op.create_index(op.f('ix_employee_scan_log_scan_id'), 'employee_scan_log', ['scan_id'], unique=False)
    op.create_table('ordered_products',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_table.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_table('planning_job',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.Enum('MAINTENANCE', 'INSTALL', name='planning_job_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'COMPLETED', name='planning_job_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_order_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('job_date', sa.String(length=10), nullable=False),
    sa.Column('time_in', sa.String(length=20), nullable=True),
    sa.Column('time_out', sa.String(length=20), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('billable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prepared_by'], ['user_table.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['order_table.order_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_planning_job_created_by'), 'planning_job', ['created_by'], unique=False)
    op.create_index(op.f('ix_planning_job_event_id'), 'planning_job', ['event_id'], unique=False)
    op.create_index(op.f('ix_planning_job_job_date'), 'planning_job', ['job_date'], unique=False)
    op.create_index(op.f('ix_planning_job_job_name'), 'planning_job', ['job_name'], unique=False)
    op.create_index(op.f('ix_planning_job_plan_id'), 'planning_job', ['plan_id'], unique=False)
    op.create_index(op.f('ix_planning_job_plan_type'), 'planning_job', ['plan_type'], unique=False)
    op.create_index(op.f('ix_planning_job_prepared_by'), 'planning_job', ['prepared_by'], unique=False)
    op.create_index(op.f('ix_planning_job_status'), 'planning_job', ['status'], unique=False)
    op.create_index(op.f('ix_planning_job_work_order_id'), 'planning_job', ['work_order_id'], unique=False)
    op.create_table('product_note',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user_table.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_product_note_admin_id'), 'product_note', ['admin_id'], unique=False)
    op.create_index(op.f('ix_product_note_note_id'), 'product_note', ['note_id'], unique=False)
    op.create_index(op.f('ix_product_note_product_id'), 'product_note', ['product_id'], unique=False)
    op.create_table('planning_cost_entry',
    sa.Column('cost_entry_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('cost_type', sa.Enum('EQUIPMENT', 'GREEN_GOODS', 'HARD_GOODS', name='planning_cost_type_enum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('planned_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('actual_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_total >= 0', name='planning_cost_actual_total_nonnegative'),
    sa.CheckConstraint('hours IS NULL OR hours >= 0', name='planning_cost_hours_nonnegative'),
    sa.CheckConstraint('planned_total >= 0', name='planning_cost_planned_total_nonnegative'),
    sa.CheckConstraint('quantity >= 0', name='planning_cost_quantity_nonnegative'),
    sa.CheckConstraint('unit_cost >= 0', name='planning_cost_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['plan_id'], ['planning_job.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cost_entry_id')
    )
    op.create_index(op.f('ix_planning_cost_entry_cost_entry_id'), 'planning_cost_entry', ['cost_entry_id'], unique=False)
    op.create_index(op.f('ix_planning_cost_entry_cost_type'), 'planning_cost_entry', ['cost_type'], unique=False)
    op.create_index(op.f('ix_planning_cost_entry_plan_id'), 'planning_cost_entry', ['plan_id'], unique=False)
    op.create_table('planning_labor_entry',
    sa.Column('labor_entry_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_hours >= 0', name='planning_labor_actual_hours_nonnegative'),
    sa.CheckConstraint('hourly_rate >= 0', name='planning_labor_hourly_rate_nonnegative'),
    sa.CheckConstraint('planned_hours >= 0', name='planning_labor_planned_hours_nonnegative'),
    sa.ForeignKeyConstraint(['employee_id'], ['user_table.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['planning_job.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('labor_entry_id')
    )
    op.create_index(op.f('ix_planning_labor_entry_category'), 'planning_labor_entry', ['category'], unique=False)
    op.create_index(op.f('ix_planning_labor_entry_employee_id'), 'planning_labor_entry', ['employee_id'], unique=False)
    op.create_index(op.f('ix_planning_labor_entry_labor_entry_id'), 'planning_labor_entry', ['labor_entry_id'], unique=False)
    op.create_index(op.f('ix_planning_labor_entry_plan_id'), 'planning_labor_entry', ['plan_id'], unique=False)
    # ### end Alembic commands ###


EXTRA_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_order_table_status ON order_table(status)",
    "CREATE INDEX IF NOT EXISTS idx_order_table_ordered_at ON order_table(ordered_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_order_table_status_ordered_at ON order_table(status, ordered_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_ordered_products_order_id ON ordered_products(order_id)",
    "CREATE INDEX IF NOT EXISTS idx_ordered_products_product_id ON ordered_products(product_id)",
    "CREATE INDEX IF NOT EXISTS idx_product_item_name ON product(item_name)",
    "CREATE INDEX IF NOT EXISTS idx_product_section ON product(section)",
    "CREATE INDEX IF NOT EXISTS idx_product_nursery_item_name ON product(nursery_id, item_name)",
    "CREATE INDEX IF NOT EXISTS idx_notification_created_at ON notification(created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_notification_reference_id ON notification(reference_id)",
    "CREATE INDEX IF NOT EXISTS idx_notification_type ON notification(type)",
    "CREATE INDEX IF NOT EXISTS idx_product_submission_status ON product_submission(status)",
    "CREATE INDEX IF NOT EXISTS idx_product_submission_created_at ON product_submission(created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_product_submission_status_created_at ON product_submission(status, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_employee_scan_log_order_product ON employee_scan_log(order_id, product_id)",
    "CREATE INDEX IF NOT EXISTS idx_employee_scan_log_employee_scanned_at ON employee_scan_log(employee_id, scanned_at DESC)",
]


def upgrade() -> None:
    if sa.inspect(op.get_bind()).has_table("user_table"):
        # Pre-Alembic database: catch it up with the legacy sync, then just stamp this revision.
        from app.core.schema_sync import sync_schema

        sync_schema()
        return

    _create_baseline()
    op.create_check_constraint(
        "order_table_work_order_type_check", "order_table", "work_order_type in ('MAINTENANCE', 'INSTALL')"
    )
    for statement in EXTRA_INDEXES:
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_labor_entry_plan_id'), table_name='planning_labor_entry')
    op.drop_index(op.f('ix_planning_labor_entry_labor_entry_id'), table_name='planning_labor_entry')
    op.drop_index(op.f('ix_planning_labor_entry_employee_id'), table_name='planning_labor_entry')
    op.drop_index(op.f('ix_planning_labor_entry_category'), table_name='planning_labor_entry')
    op.drop_table('planning_labor_entry')
    op.drop_index(op.f('ix_planning_cost_entry_plan_id'), table_name='planning_cost_entry')
    op.drop_index(op.f('ix_planning_cost_entry_cost_type'), table_name='planning_cost_entry')
    op.drop_index(op.f('ix_planning_cost_entry_cost_entry_id'), table_name='planning_cost_entry')
    op.drop_table('planning_cost_entry')
    op.drop_index(op.f('ix_product_note_product_id'), table_name='product_note')
    op.drop_index(op.f('ix_product_note_note_id'), table_name='product_note')
    op.drop_index(op.f('ix_product_note_admin_id'), table_name='product_note')
    op.drop_table('product_note')
    op.drop_index(op.f('ix_planning_job_work_order_id'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_status'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_prepared_by'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_plan_type'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_plan_id'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_job_name'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_job_date'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_event_id'), table_name='planning_job')
    op.drop_index(op.f('ix_planning_job_created_by'), table_name='planning_job')
    op.drop_table('planning_job')
    op.drop_table('ordered_products')
    op.drop_index(op.f('ix_employee_scan_log_scan_id'), table_name='employee_scan_log')
    op.drop_index(op.f('ix_employee_scan_log_product_id'), table_name='employee_scan_log')
    op.drop_index(op.f('ix_employee_scan_log_order_id'), table_name='employee_scan_log')
    op.drop_index(op.f('ix_employee_scan_log_employee_id'), table_name='employee_scan_log')
    op.drop_table('employee_scan_log')
    op.drop_index(op.f('ix_product_submission_submission_id'), table_name='product_submission')
    op.drop_index(op.f('ix_product_submission_reviewed_by'), table_name='product_submission')
    op.drop_index(op.f('ix_product_submission_nursery_id'), table_name='product_submission')
    op.drop_index(op.f('ix_product_submission_employee_id'), table_name='product_submission')
    op.drop_index(op.f('ix_product_submission_barcode_printed_by'), table_name='product_submission')
    op.drop_index(op.f('ix_product_submission_approved_product_id'), table_name='product_submission')
    op.drop_table('product_submission')
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_nursery_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_table_user_id'), table_name='order_table')
    op.drop_index(op.f('ix_order_table_order_id'), table_name='order_table')
    op.drop_table('order_table')
    op.drop_index(op.f('ix_zone_configuration_zone_number'), table_name='zone_configuration')
    op.drop_table('zone_configuration')
    op.drop_index(op.f('ix_user_table_user_username'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_user_id'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_index(op.f('ix_nursery_nursery_id'), table_name='nursery')
    op.drop_table('nursery')
    op.drop_index(op.f('ix_notification_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_event_table_event_id'), table_name='event_table')
    op.drop_table('event_table')
    # ### end Alembic commands ###
